// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz80aYRPQJ1MDBJNozVMAyUkWTcuK5M10',
    appId: '1:177555612532:web:d9ba5dc121c66748b64221',
    messagingSenderId: '177555612532',
    projectId: 'chatapp-6cb67',
    authDomain: 'chatapp-6cb67.firebaseapp.com',
    storageBucket: 'chatapp-6cb67.appspot.com',
    measurementId: 'G-BS9K4N1B7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0rU3KOiZYMhSu1mt0eFqmKJcee_e_aA',
    appId: '1:177555612532:android:ba46ce038a18cddbb64221',
    messagingSenderId: '177555612532',
    projectId: 'chatapp-6cb67',
    storageBucket: 'chatapp-6cb67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefy6eUTv7Lfly1uCtr5vcm1Jt_PWAWI8',
    appId: '1:177555612532:ios:8ef65914c9841e4fb64221',
    messagingSenderId: '177555612532',
    projectId: 'chatapp-6cb67',
    storageBucket: 'chatapp-6cb67.appspot.com',
    iosBundleId: 'com.example.somniaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefy6eUTv7Lfly1uCtr5vcm1Jt_PWAWI8',
    appId: '1:177555612532:ios:8ef65914c9841e4fb64221',
    messagingSenderId: '177555612532',
    projectId: 'chatapp-6cb67',
    storageBucket: 'chatapp-6cb67.appspot.com',
    iosBundleId: 'com.example.somniaTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz80aYRPQJ1MDBJNozVMAyUkWTcuK5M10',
    appId: '1:177555612532:web:8e55bf95f3fd8582b64221',
    messagingSenderId: '177555612532',
    projectId: 'chatapp-6cb67',
    authDomain: 'chatapp-6cb67.firebaseapp.com',
    storageBucket: 'chatapp-6cb67.appspot.com',
    measurementId: 'G-HFEZDR3GD9',
  );

}